<?php
use Packaged\Dispatch\AssetManager;
use App\Application\Infrastructure\Components\Analytics\GoogleAnalytics;
use App\Application\Infrastructure\Meta\Personal;

?>
<!DOCTYPE html>
<html lang="en">
<head>
  <base href="/">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="fragment" content="!">
  <meta name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title><?= $this->getData('title', Personal::NAME . ' - Portfolio'); ?></title>
  <?= $this->getData('metaTags'); ?>

  <!-- global CSS assets and Favicon -->
  <?= $this->getData('css'); ?>
  <!-- page CSS -->
  <?= AssetManager::generateHtmlIncludes(AssetManager::TYPE_CSS); ?>
</head>

<body>
<?= $this->getData('googleAnalytics', GoogleAnalytics::i()); ?>

<?= $this->content(); ?>

<!-- global JS -->
<?= $this->getData('js'); ?>
<!-- page JS -->
<?= AssetManager::generateHtmlIncludes('js'); ?>
</body>
</html>
